version: 2

jobs:
  build_and_test:
    docker:
      - image: ubuntu:latest
    steps:
      - checkout
      - run: ./.circleci/prepare_build.sh -DBUILD_TESTS=ON -DBUILD_EXAMPLES=ON
      - run: make -C build/
      - run: ./build/test/test_suite
      - run: ./build/test/test_suite_ipc
      - run: ./build/test/test_suite_udt
      - run: ./build/test/test_suite_gzip

workflows:
   version: 2
   build_and_test:
     jobs:
       - build_and_test
